name:        Arman Behnam
title:       Arman Behnam
description: Co-Founder of Quis and CS PhD at Illinois Tech, working on AI-human understanding and causal machine learning.
url:         https://armanbehnam.github.io
baseurl:     ""

author:
  name:  Arman Behnam
  email: abehnam@hawk.iit.edu

markdown:  kramdown
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-sitemap
